config/routes.rb
Rails.application.routes.draw do
  resources :jits
  resources :forums
  resources :twerps
  root to: 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/forum.rb
class Forum < ApplicationRecord
end

app/models/jit.rb
class Jit < ApplicationRecord
end

app/models/twerp.rb
class Twerp < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: %i[ show edit update destroy ]

  # GET /forums or /forums.json
  def index
    @forums = Forum.all
  end

  # GET /forums/1 or /forums/1.json
  def show
  end

  # GET /forums/new
  def new
    @forum = Forum.new
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums or /forums.json
  def create
    @forum = Forum.new(forum_params)

    respond_to do |format|
      if @forum.save
        format.html { redirect_to forum_url(@forum), notice: "Forum was successfully created." }
        format.json { render :show, status: :created, location: @forum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1 or /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to forum_url(@forum), notice: "Forum was successfully updated." }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1 or /forums/1.json
  def destroy
    @forum.destroy

    respond_to do |format|
      format.html { redirect_to forums_url, notice: "Forum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def forum_params
      params.require(:forum).permit(:name)
    end
end

app/controllers/jits_controller.rb
class JitsController < ApplicationController
  before_action :set_jit, only: %i[ show edit update destroy ]

  # GET /jits or /jits.json
  def index
    @jits = Jit.all
  end

  # GET /jits/1 or /jits/1.json
  def show
  end

  # GET /jits/new
  def new
    @jit = Jit.new
  end

  # GET /jits/1/edit
  def edit
  end

  # POST /jits or /jits.json
  def create
    @jit = Jit.new(jit_params)

    respond_to do |format|
      if @jit.save
        format.html { redirect_to jit_url(@jit), notice: "Jit was successfully created." }
        format.json { render :show, status: :created, location: @jit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @jit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jits/1 or /jits/1.json
  def update
    respond_to do |format|
      if @jit.update(jit_params)
        format.html { redirect_to jit_url(@jit), notice: "Jit was successfully updated." }
        format.json { render :show, status: :ok, location: @jit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @jit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jits/1 or /jits/1.json
  def destroy
    @jit.destroy

    respond_to do |format|
      format.html { redirect_to jits_url, notice: "Jit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jit
      @jit = Jit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def jit_params
      params.require(:jit).permit(:content, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/twerps_controller.rb
class TwerpsController < ApplicationController
  before_action :set_twerp, only: %i[ show edit update destroy ]

  # GET /twerps or /twerps.json
  def index
    @twerps = Twerp.all
  end

  # GET /twerps/1 or /twerps/1.json
  def show
  end

  # GET /twerps/new
  def new
    @twerp = Twerp.new
  end

  # GET /twerps/1/edit
  def edit
  end

  # POST /twerps or /twerps.json
  def create
    @twerp = Twerp.new(twerp_params)

    respond_to do |format|
      if @twerp.save
        format.html { redirect_to twerp_url(@twerp), notice: "Twerp was successfully created." }
        format.json { render :show, status: :created, location: @twerp }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @twerp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twerps/1 or /twerps/1.json
  def update
    respond_to do |format|
      if @twerp.update(twerp_params)
        format.html { redirect_to twerp_url(@twerp), notice: "Twerp was successfully updated." }
        format.json { render :show, status: :ok, location: @twerp }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @twerp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twerps/1 or /twerps/1.json
  def destroy
    @twerp.destroy

    respond_to do |format|
      format.html { redirect_to twerps_url, notice: "Twerp was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twerp
      @twerp = Twerp.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def twerp_params
      params.require(:twerp).permit(:name, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/jits_helper.rb
module JitsHelper
end

app/helpers/twerps_helper.rb
module TwerpsHelper
end

app/views/forums/_form.html.erb
<%= form_with(model: forum) do |form| %>
  <% if forum.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

      <ul>
        <% forum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/forums/_forum.html.erb
<div id="<%= dom_id forum %>">
  <p>
    <strong>Name:</strong>
    <%= forum.name %>
  </p>

</div>

app/views/forums/edit.html.erb
<h1>Editing forum</h1>

<%= render "form", forum: @forum %>

<br>

<div>
  <%= link_to "Show this forum", @forum %> |
  <%= link_to "Back to forums", forums_path %>
</div>

app/views/forums/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Forums</h1>

<div id="forums">
  <% @forums.each do |forum| %>
    <%= render forum %>
    <p>
      <%= link_to "Show this forum", forum %>
    </p>
  <% end %>
</div>

<%= link_to "New forum", new_forum_path %>

app/views/forums/new.html.erb
<h1>New forum</h1>

<%= render "form", forum: @forum %>

<br>

<div>
  <%= link_to "Back to forums", forums_path %>
</div>

app/views/forums/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @forum %>

<div>
  <%= link_to "Edit this forum", edit_forum_path(@forum) %> |
  <%= link_to "Back to forums", forums_path %>

  <%= button_to "Destroy this forum", @forum, method: :delete %>
</div>

app/views/jits/_form.html.erb
<%= form_with(model: jit) do |form| %>
  <% if jit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(jit.errors.count, "error") %> prohibited this jit from being saved:</h2>

      <ul>
        <% jit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/jits/_jit.html.erb
<div id="<%= dom_id jit %>">
  <p>
    <strong>Content:</strong>
    <%= jit.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= jit.user_id %>
  </p>

</div>

app/views/jits/edit.html.erb
<h1>Editing jit</h1>

<%= render "form", jit: @jit %>

<br>

<div>
  <%= link_to "Show this jit", @jit %> |
  <%= link_to "Back to jits", jits_path %>
</div>

app/views/jits/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Jits</h1>

<div id="jits">
  <% @jits.each do |jit| %>
    <%= render jit %>
    <p>
      <%= link_to "Show this jit", jit %>
    </p>
  <% end %>
</div>

<%= link_to "New jit", new_jit_path %>

app/views/jits/new.html.erb
<h1>New jit</h1>

<%= render "form", jit: @jit %>

<br>

<div>
  <%= link_to "Back to jits", jits_path %>
</div>

app/views/jits/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @jit %>

<div>
  <%= link_to "Edit this jit", edit_jit_path(@jit) %> |
  <%= link_to "Back to jits", jits_path %>

  <%= button_to "Destroy this jit", @jit, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Jitter App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <!-- DELETE THIS LINE 1/4 
    <link href=
"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css"
        rel="stylesheet" integrity=
"sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU"
        crossorigin="anonymous" />

      DELETE THIS LINE 2/4 -->
  </head>

  <body>
    <%= yield %>

      <!-- DELETE THIS LINE 3/4
      
    <script src=
"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity=
"sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous">
      
      DELETE THIS LINE 4/4 -->
  </body>
</html>

app/views/pages/home.html.erb
<h2>Welcome to the BEST Jitter Homepage! </h2>

<a href="/twerps">Click here to go to the Twerps</a>

app/views/twerps/_extraTwerpCode.erb
  <p>
    <strong>Most recently Twerped:</strong>
    <% allTwerp = Twerp.all %>
    <% last = Twerp.last %>
    <%= last.content %> 
      
  </p>

  <p>
    <strong>Created:</strong>
    <%= twerp.created_at %>
  </p>


  <p>
    <strong>Updated:</strong>
    <%= twerp.updated_at %>
  </p>

app/views/twerps/_form.html.erb
<%= form_with(model: twerp) do |form| %>
  <% if twerp.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(twerp.errors.count, "error") %> prohibited this twerp from being saved:</h2>

      <ul>
        <% twerp.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/twerps/_twerp.html.erb
<div id="<%= dom_id twerp %>">
  <p>
    <strong>Name:</strong>
    <%= twerp.name %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= twerp.content.upcase %>
  </p>



</div>

app/views/twerps/edit.html.erb
<h1>Editing twerp</h1>

<%= render "form", twerp: @twerp %>

<br>

<div>
  <%= link_to "Show this twerp", @twerp %> |
  <%= link_to "Back to twerps", twerps_path %>
</div>

app/views/twerps/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Twerps</h1>

<div id="twerps">
  <% @twerps.each do |twerp| %>
    <%= render twerp %>
    <p>
      <%= link_to "Show this twerp", twerp %>
    </p>
  <% end %>
</div>

<%= link_to "New twerp", new_twerp_path %>

app/views/twerps/new.html.erb
<h1>New twerp</h1>

<%= render "form", twerp: @twerp %>

<br>

<div>
  <%= link_to "Back to twerps", twerps_path %>
</div>

app/views/twerps/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @twerp %>

<div>
  <%= link_to "Edit this twerp", edit_twerp_path(@twerp) %> |
  <%= link_to "Back to twerps", twerps_path %>

  <%= button_to "Destroy this twerp", @twerp, method: :delete %>
</div>